[versions]

micronaut = "4.0.0-M1"
micronaut-docs = "2.0.0"
micronaut-test = "4.0.0-SNAPSHOT"

groovy = "4.0.10"
spock = "2.3-groovy-4.0"
jaxb-api = "2.3.1"

[libraries]

jackson-dataformat-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml" }
jaxb-api = { module = "javax.xml.bind:jaxb-api", version.ref = "jaxb-api" }
